[18.0][MIG] base_report_to_label_printer: Migration to 18.0
Kimkhoi3010/report-print-send pull request #1
Opened 2024-10-15 10:40 UTC by Kimkhoi3010

Depend on: [[18.0][MIG] base_report_to_printer: Migration to 18.0](https://github.com/OCA/report-print-send/pull/371)

2024-10-15 11:49 UTC, xaviedoanhduy requested changes

2024-10-15 11:49 UTC, xaviedoanhduy commented on base_report_to_label_printer/models/res_users.py
> +        self.SELF_WRITEABLE_FIELDS.extend(["default_label_printer_id"])
should override `SELF_READABLE_FIELDS` and  `SELF_WRITEABLE_FIELDS` property https://github.com/odoo/odoo/blob/09fa1db600c31d2d04f0504f0412cbbc85ff7e3d/odoo/addons/base/models/res_users.py#L351

2024-10-15 11:49 UTC, xaviedoanhduy commented on base_report_to_label_printer/models/res_users.py
> +    @api.model
```suggestion
```
no need this decorator

2024-10-15 11:51 UTC, xaviedoanhduy commented
btw, can you squash the commit in the next update?

2024-10-16 03:56 UTC, xaviedoanhduy approved these changes
LGTM (code review)

2024-10-21 07:41 UTC, nilshamerlinck commented
`test-requirements.txt` content looks odd, please check again

2025-04-29 12:07 UTC, merged